### ISSUE TITLE
Set PR status with details of failed checks

### ISSUE THREAD

**Issue by alekseykulikov** [treosh/lighthouse-ci-action#11]

**Comment by imbsky** [comment]
> integrate with PR status (display scores, fail PR but upload results)

I like this!

**Comment by imbsky** [comment]
This design and code are probably helpful.
https://twitter.com/orta/status/1192847477516439554

**Comment by alekseykulikov** [comment]
Fixed in [2.3.0](https://github.com/treosh/lighthouse-ci-action/releases/tag/2.3.0)
