### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by kushalmahajan** [treosh/lighthouse-ci-action#112]
Below is how annotation looks when the action runs successfully. However, it only shows warnings and no significant output on workflow section or annotation itself. By workflow section I mean similar to the section as Artifacts. 

Expectation is to have output which matches as mentioned on Node.js 12 actions are deprecated

Plus, could you let me know if there is a way we can post this result on a PR and prevent merging it if failed. 

<img width="1420" alt="Screenshot 2022-10-20 at 2 47 23 PM" src="https://user-images.githubusercontent.com/11805936/196909160-d1ee1828-c716-4a3d-80e1-cedddd140847.png">

**Comment by solidevolution** [comment]
I updated my GitHub workflow file to **actions/checkout@v3**, **actions/setup-node@v3** with pinned version **16** and **treosh/lighthouse-ci-action@v9** to remove the warnings.
