### ISSUE TITLE
New Bfcache audit in Lighthouse 10 fails

### ISSUE THREAD

**Issue by tunetheweb** [treosh/lighthouse-ci-action#126]
We saw the same thing in WebPageTest and moved to the new headless option which solved it:
https://github.com/WPO-Foundation/wptagent/pull/605

Is that an option here?

**Comment by brendankenny** [comment]
Looking at the lighthouse-ci code, it's not (AFAICT) possible to tell it to use `--headless=new` currently. I [opened a PR](https://github.com/GoogleChrome/lighthouse-ci/pull/907) to automatically use the new headless mode when run headlessly.
