### ISSUE TITLE
Action incorrectly failing when using `includePassedAssertions`

### ISSUE THREAD

**Issue by KaiDoering** [treosh/lighthouse-ci-action#130]
When the flag `includePassedAssertions` is used in lighthouserc the action will fail, because it is assumed that the assertion result files only contains failed results. Filtering for results with `passed: false` should fix this.

Minimal lighthouserc.js to reproduce:

```
module.exports = {
    ci: {
        assert: {
            includePassedAssertions: true,
            assertions: {
                "categories:performance": ["error", { minScore: 0.01 }],
            },
        },
    },
};
```

**Comment by gregoriopalama** [comment]
Any plan on when this will be merged?

**Comment by alekseykulikov** [comment]
Could you provide a PR? Thanks!
