### ISSUE TITLE
Update lighthouse to v0.13.0

### ISSUE THREAD

**Issue by gmerwan** [treosh/lighthouse-ci-action#136]
Hello team 👋🏻 
`lighthouse-ci` v0.13.0 has been released around December 2023, which includes the `lighthouse` v11.4.0
https://github.com/GoogleChrome/lighthouse-ci/releases/tag/v0.13.0

Any plans for upgrading ?

**Comment by alekseykulikov** [comment]
yep, also `node` should be upgraded to v20

**Comment by gmerwan** [comment]
Thanks a lot for taking care of updating the dependencies quickly 🙏🏻
