### ISSUE TITLE
Allow use of YAML config files

### ISSUE THREAD

**Issue by Snugug** [treosh/lighthouse-ci-action#23]
I've got a `yaml` `lighthouserc` file, and it throws the following error which leads me to believe it only currently works with `json` files:

```
Run treosh/lighthouse-ci-action@v2
undefined:1
ci:
^

SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
```

**Comment by alekseykulikov** [comment]
thanks for a bug report,  it will be fixed in upcoming [2.3.0 release](https://github.com/treosh/lighthouse-ci-action/releases)
