### ISSUE TITLE
Check URLs after Travis deploy

### ISSUE THREAD

**Issue by kaihendry** [treosh/lighthouse-ci-action#26]
I deploy via [Travis CI](https://github.com/kaihendry/ltabus/blob/master/.travis.yml), so how do I express that I want this to run **after** travis deployment?
https://s.natalian.org/2020-01-24/order-dependency.mp4

Thank you in advance,

**Comment by alekseykulikov** [comment]
Hey, Github Action is a replacement for Travis, I'm not sure it's possible to get confirmation from external service. You could try to configure the raw Lighthouse CI: https://github.com/GoogleChrome/lighthouse-ci/blob/93b674203a39520d40f6c985048d83d2ed46a2b8/docs/getting-started.md
