### ISSUE TITLE
Return JSON, not HTML

### ISSUE THREAD

**Issue by irfan-maulana-tkp** [treosh/lighthouse-ci-action#27]
Is there any sample using this action to return JSON response and not HTML file?

**Comment by alekseykulikov** [comment]
Yes, by default LHCI generates `.json` and `.html` files, for example:

```bash
ls .lighthouseci
lhr-1583503541026.html  
lhr-1583503541026.json  
lhr-1583503555882.html  
lhr-1583503555882.json
```

If you upload results using as [an artifact](https://github.com/treosh/lighthouse-ci-action/blob/master/.github/workflows/LHCI-upload-artifact.yml) or as a gist, it's a JSON file.
