### ISSUE TITLE
Report server URLs to PR

### ISSUE THREAD

**Issue by Snugug** [treosh/lighthouse-ci-action#28]
I'd like the ability to have this post the links to the reports in the PR

**Comment by denar90** [comment]
Hey, we are on it :) You can keep eye on #22. Should be part of that PR also.

**Comment by alekseykulikov** [comment]
With the latest [2.3.0](https://github.com/treosh/lighthouse-ci-action/releases/tag/2.3.0) release, report URLs are the part of annotations about failed tests.

For Temporary Storage:
![image](https://user-images.githubusercontent.com/158189/77120762-e3750a80-6a39-11ea-99fd-887e93db5f29.png)

For LHCI Server:
![image](https://user-images.githubusercontent.com/158189/77120771-e839be80-6a39-11ea-8f77-210b5aa00229.png)
