### ISSUE TITLE
Use with field-plugin examples

### ISSUE THREAD

**Issue by staabm** [treosh/lighthouse-ci-action#42]
How to combine the github action with the field plugin https://github.com/treosh/lighthouse-plugin-field-performance ?

**Comment by alekseykulikov** [comment]
The action supports LH plugins, and we even had an example: https://github.com/treosh/lighthouse-ci-action/pull/19/files#diff-04c6e90faac2675aa89e2176d2eec7d8R392
I will recover the recipe using a field-plugin.

**Comment by alekseykulikov** [comment]
done https://github.com/treosh/lighthouse-ci-action/actions?query=workflow%3ALHCI-lighthouse-plugin
