### ISSUE TITLE
setting configPath leads to "Cannot find module"

### ISSUE THREAD

**Issue by paulirish** [treosh/lighthouse-ci-action#47]
the configPath is loaded relative to the action's own sourcecode.

In this commit https://github.com/ChromeDevTools/debugger-protocol-viewer/commit/27154fb38db8dfcc620f3bf60b841a3aad4dad47 ...

you can see `configPath: ./.lighthouserc.js`

I was attempting to reference the `.lighthouserc.js` you see in the same commit.
But it failed to find it:
![image](https://user-images.githubusercontent.com/39191/78944481-d9f82480-7a72-11ea-8229-3acef314a835.png)
[(run link)](https://github.com/ChromeDevTools/debugger-protocol-viewer/runs/575335562)

probably because these lines expect a path that resolves from cwd/pwd: https://github.com/treosh/lighthouse-ci-action/blob/65160cbe7b83b16f57e39eef26e26a28bc720e16/src/config.js#L28-L29

The readme has the example of `configPath: ./lighthouserc.json` so i figured it would be read local to my checkout instead of local to the action's source.

some path.resolve() should sort this out?

**Comment by alekseykulikov** [comment]
fixed in `treosh/lighthouse-ci-action@v3`

**Comment by alekseykulikov** [comment]
For some reason, the bug only affects `.js` config files.
Starting to use `.js` files in test workflows in addition to `.json`.
