### ISSUE TITLE
Do action parameters override settings parameters?

### ISSUE THREAD

**Issue by anton-tproger-crimea** [treosh/lighthouse-ci-action#80]
Actions has at least two parameters that replicate the ones present on LHCI config:
* https://github.com/treosh/lighthouse-ci-action#urls and https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#url
* https://github.com/treosh/lighthouse-ci-action#runs-default-1 and https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#numberofruns

Which of them do have priority if both specified? Looks like action params override configuration options from config file but please confirm explicitly. What if action param is not specified? Will it use value from config file or use its own default (e.g. action runs=1 by default)?

Also huge thanks for an awesome tool! Great job 👍

**Comment by anton-tproger** [comment]
I have run some tests and looks like if configuration is not set using action parameters, the settings are fetched from config file which is what expected. I still suggest adding this explicitly to README.
