### ISSUE TITLE
dynamic urls list

### ISSUE THREAD

**Issue by bennypowers** [treosh/lighthouse-ci-action#95]
Say I want to send the list of urls in a webhook, or calculate it based on some state in my repo, or define it using a javascript function. 

It would be great to be able to dynamically build the list of urls.

Cheers

**Comment by davidsneighbour** [comment]
perfect. that is worth a mention in the sample workflows section. @alekseykulikov

**Comment by alekseykulikov** [comment]
I'd love to add it as a recipe: https://github.com/treosh/lighthouse-ci-action#recipes
Don't you mind making a PR to docs?
